### ISSUE TITLE
How to show with size?

### ISSUE THREAD

**Issue by tuan97anton** [xwying/torchshow#1]
How to show with size?
ex, in matplotlib , I config `plt.figure(figsize=(10,10))`

**Comment by xwying** [comment]
Specifying the `figsize` is not supported in the current version (0.4.1), because the figure is created by calling `plt.subplots()`. I did not think of this feature when developing the package since I usually use it with an iterative backend and I can just manually adjust the window size. 

https://github.com/xwying/torchshow/blob/868f404c6c1ec319557db506ada8bf1c08f9a2fe/torchshow/visualization.py#L108

However, I think this feature can be easily supported if will be helpful. May I ask what is your use case for this feature?

**Comment by tuan97anton** [comment]
Simply, I want to show features bigger
![Screenshot from 2022-06-15 11-19-40](https://user-images.githubusercontent.com/28828102/173736154-96757970-e98c-4bd9-80f8-55b34330aedc.png)
.

**Comment by xwying** [comment]
I see. So you are using it in a Jupyter notebook which has non-interactive backend by default.

I'll implement the support recently. I'll close this issue once it is done. For now maybe try to see if you can activate an interactive backend. For example, `%matplotlib notebook` (found on internet but haven't tested this by myself)
