### ISSUE TITLE
How to show image in debug mod when connect to SSH server in VScode?

### ISSUE THREAD

**Issue by pmzzs** [xwying/torchshow#12]
I try to use this command in debug console with VScode jupyter:

ts.show(random_batch[0])

but return None and no image window pops up

**Comment by xwying** [comment]
Thank you for using TorchShow! 

To display any GUI (e.g. the matplotlib window) over ssh you will need to enable X11 forwarding, which is handled by the system rather than TorchShow. There should be plenty of tutorials online about this. Depending on your operating systems the steps may be a little bit different but usually you need to modify a few ssh configs on remote server to allow X11 forwarding and then connect to the server using `ssh` with the `-X` (for normal X11 forwarding) or `-Y` (for trusted X11 forwarding) flag.

Once it has been set up, you can try to run any GUI applications such as `xeyes` on the command line on your remote system to see if it can connect to your display.

Hope it helps!
