### ISSUE TITLE
Show a single video in a grid layout?

### ISSUE THREAD

**Issue by xuchenhao001** [xwying/torchshow#15]
Thank you so much for your project! It really saves me time in visualizing PyTorch tensors. Do you have any plan to show a single video in a grid layout like [this](https://pytorch.org/vision/main/auto_examples/plot_video_api.html#data-visualization)?

**Comment by xwying** [comment]
Glad to hear that TorchShow was helpful! What you described was already supported since a video is just a list of images. Please refer to [this document](https://github.com/xwying/torchshow#3-visualizing-batch-of-tensors). Also if you make use of the `axes_title` parameter (which can be found in the [API](https://github.com/xwying/torchshow/blob/master/API.md)), you can do even more such as showing the frame id on each frame.

**Comment by xuchenhao001** [comment]
It surely works well! Nice project!
