### ISSUE TITLE
Why should we use this library?

### ISSUE THREAD

**Issue by kadirnar** [xwying/torchshow#2]
Hi @xwying ,

Is there a speed difference compared to other libraries? What are the advantages?

**Comment by xwying** [comment]
Hi @kadirnar , this package is created to save my time when debugging CV projects. I like to set breakpoints in my code and examine some tensors frequently (e.g. feature maps, input data after augmentation, intermediate output, etc.). As you can see from the documentation, usually you need to do a bunch of conversions before you can actually plot it. 

Torchshow just saves you time and brain cells by providing a simple API and does all the conversion for you. Under the hood, it still uses Matplotlib to display the figure.

BTW, what are "other libraries" you are referring to? I created this package because I didn't see one with similar functionality.

**Comment by xwying** [comment]
I thought about adding different backends but so far the plt works pretty well for the purpose of this package. Adding another backend may requires a bunch of work to support some features such as [grid layout](https://github.com/xwying/torchshow#5-visualizing-multiple-tensors-with-custom-layout) and [pixel examination](https://github.com/xwying/torchshow#6-examine-the-pixel-with-richer-information). 

Can you elaborate on your use case? If you just want to use the auto-conversion feature in torchshow, maybe we can make ts.show() return the `plot_list` (the converted np.array images) as well. 

https://github.com/xwying/torchshow/blob/c065dba8c1f76071a7194c60775001eaa3b2b0f4/torchshow/torchshow.py#L87-L97

This way, we can further plot them using any other library such as opencv or PIL. Maybe something like this:

```python
plots = ts.show(tensor, display=False).
cv2.imshow('img', plots[0])
```

**Comment by kadirnar** [comment]
I will try this in my project. Thank you.
